theme: jekyll-theme-minimal

markdown: kramdown
permalink: pretty

port: 8000


title: Maxim Smith

blurb: >
  I am a New York based art director, web developer, and e-commerce and marketing consultant with 10 years experience in fashion and luxury goods. My skills include; graphic design, branding, front-end web development, film, photography, animation and digital media management.
