#-------------------------------
# General Site Settings

title: Maxim Smith
description: Designer // Art Director // Web Developer
email: maximsmith@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: , url: ''}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: "Max Smith's Design portfolio and development playground"
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I am a New York based art director, web developer, and e-commerce and marketing consultant with 10 years experience in fashion and luxury goods. My skills include; graphic design, branding, front-end web development, film, photography, animation and digital media management.
skills:
- {name: , value: ''}

#-------------------------------
# Work Section

projects:
- {name: MiN NEW YORK , folder: 'proj-1', file: 'work/proj-1.html'}
- {name: 180 The Store , folder: 'proj-2', file: 'work/proj-2.html'}
- {name: FOSSIL, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: NYCFC , folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Elayne Arterbery , folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Indycar , folder: 'proj-6', file: 'work/proj-6.html'}

project-1:
- {name: MiN NEW YORK,
  folder: 'proj-1',
  file: '',
  description: '
  <p>Art Direction, Web Design, Web Development, Print & Packaging Design</p>

  <p>MiN New York is a niche luxury perfume brand based in SoHo, New York. My role primarily looked after digital, print and packaging design. I had Designed and developed the main ecommerce website (min.com), wholesale website (MiNProfessionals.com), email marketing and landing pages. I also maintained an operations management role for the flagship SoHo store, Wholesale accounts, and ecommerce platforms. Other duties included product photography, image retouching and creative direction.</p>'}

project-2:
- {name: 180 The Store,
  folder: 'proj-2',
  file: '',
  description: '<p>Web Design, Web Development, E-commerce Consultant</p>

  <p>Store and showroom, 180 The Store, based in Tribeca, NY needed an e-commerce store, having not sold online before. I have been working with the showroom to set them up to sell online, working to set up operations on the back-end as well as designing and developing the front-end store.</p>'}

project-3:
- {name: FOSSIL,
  folder: 'proj-3',
  file: '',
  description: '
  <p>Art Direction</p>

  <p>Whilst working as an art director at DMA United, the timepiece brand Fossil entrusted us to their first television commercial, focusing on their new Q Smartwatch. As the senior art director on this campaign I worked on developing this campaign from conception to delivery.</p>'}

project-4:
- {name: NYCFC,
  folder: 'proj-4',
  file: '',
  description: '
  <p>Art Direction, Digital Design, Print Design</p>
  <p>Developed (at DMA United) the inaugural advertising campaign for New York City’s MLS soccer team, NYCFC. Bringing iconic New York City street art inside Yankee Stadium and across all print and digital touch points.</p>'}

project-5:
- {name: Elayne Arterbery,
  folder: 'proj-5',
  file: '',
  description: '
  <p>Art Direction, Branding, Web Design, Packaging Design</p>
  <p>Rradiation oncologist Dr. Elayne Arterbery hired DMA United to develop and launch her own skincare line. I developed the identity, packaging and digital platform for the brand.</p>'}

project-6:
- {name: Indycar,
  folder: 'proj-6',
  file: '',
  description: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nulla justo, varius ut odio eu, facilisis eleifend risus. Phasellus in cursus sapien, ac euismod urna. Vivamus nec efficitur nibh. Maecenas lectus dui, scelerisque luctus urna in, pellentesque tincidunt augue. Duis elementum neque sollicitudin, tristique erat vel, hendrerit erat. Phasellus fringilla gravida pellentesque. Donec nec dictum turpis. Fusce est erat, dignissim interdum cursus congue, pretium vitae ipsum. Mauris non ultrices ligula, quis suscipit odio. Quisque ornare, velit eu venenatis viverra, felis purus fermentum velit, a accumsan ante justo quis eros. Donec dapibus erat nec ullamcorper eleifend. Fusce enim leo, sodales in porta eu, scelerisque quis justo. Nunc fermentum sit amet elit at vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit.<p>

<p>Aenean sed sem ut velit pharetra mattis. Fusce metus quam, pretium lacinia aliquam ut, efficitur et ipsum. Aliquam justo nulla, ultrices sit amet bibendum in, dignissim non massa. Praesent suscipit dolor augue, sit amet venenatis augue pellentesque et. Sed tempor fermentum metus semper luctus. Mauris et arcu a enim hendrerit aliquet. Ut non egestas erat. Vestibulum et accumsan dui. Pellentesque semper libero in tempor hendrerit.</p>'}


#-------------------------------
# Clients Section

clients:
- {avatar: '',
  name: '',
  title: '',
  quote: '',
  logo: ''}


#-------------------------------
# Contact Section

social:
- {title: 'email', link: 'mailto:maximsmith@gmail.com'}
- {title: 'instagram', link: 'https://www.instagram.com/maximsmith'}
- {title: 'linkedin', link: 'https://www.linkedin.com/in/max-smith-8482a848'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
