#-------------------------------
# General Site Settings

title: Maxim Smith
description: Designer // Art Director // Web Developer
email: maximsmith@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: , url: ''}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I am a New York based art director, web developer, and e-commerce and marketing consultant with 10 years experience in fashion and luxury goods. My skills include; graphic design, branding, front-end web development, film, photography, animation and digital media management.
skills:
- {name: , value: ''}

#-------------------------------
# Work Section

projects:
- {name: MiN NEW YORK , folder: 'proj-1', file: 'work/proj-1.html'}
- {name: 180 Duane , folder: 'proj-2', file: 'work/proj-2.html'}
- {name: FOSSIL, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: NYCFC , folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Elayne Arterbery , folder: 'proj-5', file: 'work/proj-5.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: '',
  name: '',
  title: '',
  quote: '',
  logo: ''}


#-------------------------------
# Contact Section

social:
- {icon: '', link: ''}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
